// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeExternalProperties = Sarif.ExternalProperties | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ExternalProperties}.
       * @example
       * expect(value).toBeValidSarifExternalProperties();
       */
      toBeValidSarifExternalProperties(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ExternalProperties}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifExternalProperties()
       * );
       */
      toBeValidSarifExternalProperties<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifExternalProperties = buildMatcher<MaybeExternalProperties>({
  matcherName: 'toBeValidSarifExternalProperties',
  definition: 'externalProperties',
});

expect.extend({ toBeValidSarifExternalProperties });
