// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeExternalPropertyFileReferences = Sarif.ExternalPropertyFileReferences | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ExternalPropertyFileReferences}.
       * @example
       * expect(value).toBeValidSarifExternalPropertyFileReferences();
       */
      toBeValidSarifExternalPropertyFileReferences(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ExternalPropertyFileReferences}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifExternalPropertyFileReferences()
       * );
       */
      toBeValidSarifExternalPropertyFileReferences<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifExternalPropertyFileReferences = buildMatcher<MaybeExternalPropertyFileReferences>(
  {
    matcherName: 'toBeValidSarifExternalPropertyFileReferences',
    definition: 'externalPropertyFileReferences',
  }
);

expect.extend({ toBeValidSarifExternalPropertyFileReferences });
