// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeFix = Sarif.Fix | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Fix}.
       * @example
       * expect(value).toBeValidSarifFix();
       */
      toBeValidSarifFix(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Fix}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifFix()
       * );
       */
      toBeValidSarifFix<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifFix = buildMatcher<MaybeFix>({
  matcherName: 'toBeValidSarifFix',
  definition: 'fix',
});

expect.extend({ toBeValidSarifFix });
