// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeMessage = Sarif.Message | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Message}.
       * @example
       * expect(value).toBeValidSarifMessage();
       */
      toBeValidSarifMessage(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Message}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifMessage()
       * );
       */
      toBeValidSarifMessage<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifMessage = buildMatcher<MaybeMessage>({
  matcherName: 'toBeValidSarifMessage',
  definition: 'message',
});

expect.extend({ toBeValidSarifMessage });
