// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeRunAutomationDetails = Sarif.RunAutomationDetails | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.RunAutomationDetails}.
       * @example
       * expect(value).toBeValidSarifRunAutomationDetails();
       */
      toBeValidSarifRunAutomationDetails(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.RunAutomationDetails}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifRunAutomationDetails()
       * );
       */
      toBeValidSarifRunAutomationDetails<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifRunAutomationDetails = buildMatcher<MaybeRunAutomationDetails>({
  matcherName: 'toBeValidSarifRunAutomationDetails',
  definition: 'runAutomationDetails',
});

expect.extend({ toBeValidSarifRunAutomationDetails });
