// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeNode = Sarif.Node | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Node}.
       * @example
       * expect(value).toBeValidSarifNode();
       */
      toBeValidSarifNode(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Node}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifNode()
       * );
       */
      toBeValidSarifNode<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifNode = buildMatcher<MaybeNode>({
  matcherName: 'toBeValidSarifNode',
  definition: 'node',
});

expect.extend({ toBeValidSarifNode });
