// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeReportingDescriptorRelationship = Sarif.ReportingDescriptorRelationship | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ReportingDescriptorRelationship}.
       * @example
       * expect(value).toBeValidSarifReportingDescriptorRelationship();
       */
      toBeValidSarifReportingDescriptorRelationship(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ReportingDescriptorRelationship}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifReportingDescriptorRelationship()
       * );
       */
      toBeValidSarifReportingDescriptorRelationship<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifReportingDescriptorRelationship = buildMatcher<MaybeReportingDescriptorRelationship>(
  {
    matcherName: 'toBeValidSarifReportingDescriptorRelationship',
    definition: 'reportingDescriptorRelationship',
  }
);

expect.extend({ toBeValidSarifReportingDescriptorRelationship });
