// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeSuppression = Sarif.Suppression | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Suppression}.
       * @example
       * expect(value).toBeValidSarifSuppression();
       */
      toBeValidSarifSuppression(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Suppression}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifSuppression()
       * );
       */
      toBeValidSarifSuppression<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifSuppression = buildMatcher<MaybeSuppression>({
  matcherName: 'toBeValidSarifSuppression',
  definition: 'suppression',
});

expect.extend({ toBeValidSarifSuppression });
