// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeStack = Sarif.Stack | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Stack}.
       * @example
       * expect(value).toBeValidSarifStack();
       */
      toBeValidSarifStack(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Stack}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifStack()
       * );
       */
      toBeValidSarifStack<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifStack = buildMatcher<MaybeStack>({
  matcherName: 'toBeValidSarifStack',
  definition: 'stack',
});

expect.extend({ toBeValidSarifStack });
