// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeConversion = Sarif.Conversion | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Conversion}.
       * @example
       * expect(value).toBeValidSarifConversion();
       */
      toBeValidSarifConversion(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Conversion}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifConversion()
       * );
       */
      toBeValidSarifConversion<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifConversion = buildMatcher<MaybeConversion>({
  matcherName: 'toBeValidSarifConversion',
  definition: 'conversion',
});

expect.extend({ toBeValidSarifConversion });
