// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeThreadFlow = Sarif.ThreadFlow | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ThreadFlow}.
       * @example
       * expect(value).toBeValidSarifThreadFlow();
       */
      toBeValidSarifThreadFlow(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ThreadFlow}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifThreadFlow()
       * );
       */
      toBeValidSarifThreadFlow<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifThreadFlow = buildMatcher<MaybeThreadFlow>({
  matcherName: 'toBeValidSarifThreadFlow',
  definition: 'threadFlow',
});

expect.extend({ toBeValidSarifThreadFlow });
