// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeTool = Sarif.Tool | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Tool}.
       * @example
       * expect(value).toBeValidSarifTool();
       */
      toBeValidSarifTool(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Tool}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifTool()
       * );
       */
      toBeValidSarifTool<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifTool = buildMatcher<MaybeTool>({
  matcherName: 'toBeValidSarifTool',
  definition: 'tool',
});

expect.extend({ toBeValidSarifTool });
