// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeMultiformatMessageString = Sarif.MultiformatMessageString | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.MultiformatMessageString}.
       * @example
       * expect(value).toBeValidSarifMultiformatMessageString();
       */
      toBeValidSarifMultiformatMessageString(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.MultiformatMessageString}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifMultiformatMessageString()
       * );
       */
      toBeValidSarifMultiformatMessageString<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifMultiformatMessageString = buildMatcher<MaybeMultiformatMessageString>({
  matcherName: 'toBeValidSarifMultiformatMessageString',
  definition: 'multiformatMessageString',
});

expect.extend({ toBeValidSarifMultiformatMessageString });
