// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeWebResponse = Sarif.WebResponse | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.WebResponse}.
       * @example
       * expect(value).toBeValidSarifWebResponse();
       */
      toBeValidSarifWebResponse(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.WebResponse}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifWebResponse()
       * );
       */
      toBeValidSarifWebResponse<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifWebResponse = buildMatcher<MaybeWebResponse>({
  matcherName: 'toBeValidSarifWebResponse',
  definition: 'webResponse',
});

expect.extend({ toBeValidSarifWebResponse });
