// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybePropertyBag = Sarif.PropertyBag | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.PropertyBag}.
       * @example
       * expect(value).toBeValidSarifPropertyBag();
       */
      toBeValidSarifPropertyBag(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.PropertyBag}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifPropertyBag()
       * );
       */
      toBeValidSarifPropertyBag<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifPropertyBag = buildMatcher<MaybePropertyBag>({
  matcherName: 'toBeValidSarifPropertyBag',
  definition: 'propertyBag',
});

expect.extend({ toBeValidSarifPropertyBag });
