// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeGraphTraversal = Sarif.GraphTraversal | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.GraphTraversal}.
       * @example
       * expect(value).toBeValidSarifGraphTraversal();
       */
      toBeValidSarifGraphTraversal(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.GraphTraversal}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifGraphTraversal()
       * );
       */
      toBeValidSarifGraphTraversal<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifGraphTraversal = buildMatcher<MaybeGraphTraversal>({
  matcherName: 'toBeValidSarifGraphTraversal',
  definition: 'graphTraversal',
});

expect.extend({ toBeValidSarifGraphTraversal });
