// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeReportingConfiguration = Sarif.ReportingConfiguration | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ReportingConfiguration}.
       * @example
       * expect(value).toBeValidSarifReportingConfiguration();
       */
      toBeValidSarifReportingConfiguration(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ReportingConfiguration}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifReportingConfiguration()
       * );
       */
      toBeValidSarifReportingConfiguration<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifReportingConfiguration = buildMatcher<MaybeReportingConfiguration>({
  matcherName: 'toBeValidSarifReportingConfiguration',
  definition: 'reportingConfiguration',
});

expect.extend({ toBeValidSarifReportingConfiguration });
