// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeExternalPropertyFileReference = Sarif.ExternalPropertyFileReference | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ExternalPropertyFileReference}.
       * @example
       * expect(value).toBeValidSarifExternalPropertyFileReference();
       */
      toBeValidSarifExternalPropertyFileReference(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ExternalPropertyFileReference}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifExternalPropertyFileReference()
       * );
       */
      toBeValidSarifExternalPropertyFileReference<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifExternalPropertyFileReference = buildMatcher<MaybeExternalPropertyFileReference>(
  {
    matcherName: 'toBeValidSarifExternalPropertyFileReference',
    definition: 'externalPropertyFileReference',
  }
);

expect.extend({ toBeValidSarifExternalPropertyFileReference });
