// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeSpecialLocations = Sarif.SpecialLocations | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.SpecialLocations}.
       * @example
       * expect(value).toBeValidSarifSpecialLocations();
       */
      toBeValidSarifSpecialLocations(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.SpecialLocations}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifSpecialLocations()
       * );
       */
      toBeValidSarifSpecialLocations<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifSpecialLocations = buildMatcher<MaybeSpecialLocations>({
  matcherName: 'toBeValidSarifSpecialLocations',
  definition: 'specialLocations',
});

expect.extend({ toBeValidSarifSpecialLocations });
