// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeReportingDescriptorReference = Sarif.ReportingDescriptorReference | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ReportingDescriptorReference}.
       * @example
       * expect(value).toBeValidSarifReportingDescriptorReference();
       */
      toBeValidSarifReportingDescriptorReference(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ReportingDescriptorReference}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifReportingDescriptorReference()
       * );
       */
      toBeValidSarifReportingDescriptorReference<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifReportingDescriptorReference = buildMatcher<MaybeReportingDescriptorReference>(
  {
    matcherName: 'toBeValidSarifReportingDescriptorReference',
    definition: 'reportingDescriptorReference',
  }
);

expect.extend({ toBeValidSarifReportingDescriptorReference });
