// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeArtifactChange = Sarif.ArtifactChange | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ArtifactChange}.
       * @example
       * expect(value).toBeValidSarifArtifactChange();
       */
      toBeValidSarifArtifactChange(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ArtifactChange}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifArtifactChange()
       * );
       */
      toBeValidSarifArtifactChange<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifArtifactChange = buildMatcher<MaybeArtifactChange>({
  matcherName: 'toBeValidSarifArtifactChange',
  definition: 'artifactChange',
});

expect.extend({ toBeValidSarifArtifactChange });
