// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeArtifactLocation = Sarif.ArtifactLocation | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ArtifactLocation}.
       * @example
       * expect(value).toBeValidSarifArtifactLocation();
       */
      toBeValidSarifArtifactLocation(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ArtifactLocation}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifArtifactLocation()
       * );
       */
      toBeValidSarifArtifactLocation<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifArtifactLocation = buildMatcher<MaybeArtifactLocation>({
  matcherName: 'toBeValidSarifArtifactLocation',
  definition: 'artifactLocation',
});

expect.extend({ toBeValidSarifArtifactLocation });
