// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeToolComponentReference = Sarif.ToolComponentReference | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ToolComponentReference}.
       * @example
       * expect(value).toBeValidSarifToolComponentReference();
       */
      toBeValidSarifToolComponentReference(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ToolComponentReference}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifToolComponentReference()
       * );
       */
      toBeValidSarifToolComponentReference<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifToolComponentReference = buildMatcher<MaybeToolComponentReference>({
  matcherName: 'toBeValidSarifToolComponentReference',
  definition: 'toolComponentReference',
});

expect.extend({ toBeValidSarifToolComponentReference });
