// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeAttachment = Sarif.Attachment | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Attachment}.
       * @example
       * expect(value).toBeValidSarifAttachment();
       */
      toBeValidSarifAttachment(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Attachment}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifAttachment()
       * );
       */
      toBeValidSarifAttachment<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifAttachment = buildMatcher<MaybeAttachment>({
  matcherName: 'toBeValidSarifAttachment',
  definition: 'attachment',
});

expect.extend({ toBeValidSarifAttachment });
