// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeAddress = Sarif.Address | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Address}.
       * @example
       * expect(value).toBeValidSarifAddress();
       */
      toBeValidSarifAddress(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Address}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifAddress()
       * );
       */
      toBeValidSarifAddress<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifAddress = buildMatcher<MaybeAddress>({
  matcherName: 'toBeValidSarifAddress',
  definition: 'address',
});

expect.extend({ toBeValidSarifAddress });
