// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybePhysicalLocation = Sarif.PhysicalLocation | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.PhysicalLocation}.
       * @example
       * expect(value).toBeValidSarifPhysicalLocation();
       */
      toBeValidSarifPhysicalLocation(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.PhysicalLocation}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifPhysicalLocation()
       * );
       */
      toBeValidSarifPhysicalLocation<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifPhysicalLocation = buildMatcher<MaybePhysicalLocation>({
  matcherName: 'toBeValidSarifPhysicalLocation',
  definition: 'physicalLocation',
});

expect.extend({ toBeValidSarifPhysicalLocation });
