// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeTranslationMetadata = Sarif.TranslationMetadata | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.TranslationMetadata}.
       * @example
       * expect(value).toBeValidSarifTranslationMetadata();
       */
      toBeValidSarifTranslationMetadata(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.TranslationMetadata}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifTranslationMetadata()
       * );
       */
      toBeValidSarifTranslationMetadata<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifTranslationMetadata = buildMatcher<MaybeTranslationMetadata>({
  matcherName: 'toBeValidSarifTranslationMetadata',
  definition: 'translationMetadata',
});

expect.extend({ toBeValidSarifTranslationMetadata });
