// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeRun = Sarif.Run | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Run}.
       * @example
       * expect(value).toBeValidSarifRun();
       */
      toBeValidSarifRun(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Run}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifRun()
       * );
       */
      toBeValidSarifRun<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifRun = buildMatcher<MaybeRun>({
  matcherName: 'toBeValidSarifRun',
  definition: 'run',
});

expect.extend({ toBeValidSarifRun });
