// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeThreadFlowLocation = Sarif.ThreadFlowLocation | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ThreadFlowLocation}.
       * @example
       * expect(value).toBeValidSarifThreadFlowLocation();
       */
      toBeValidSarifThreadFlowLocation(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ThreadFlowLocation}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifThreadFlowLocation()
       * );
       */
      toBeValidSarifThreadFlowLocation<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifThreadFlowLocation = buildMatcher<MaybeThreadFlowLocation>({
  matcherName: 'toBeValidSarifThreadFlowLocation',
  definition: 'threadFlowLocation',
});

expect.extend({ toBeValidSarifThreadFlowLocation });
