// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeNotification = Sarif.Notification | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Notification}.
       * @example
       * expect(value).toBeValidSarifNotification();
       */
      toBeValidSarifNotification(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Notification}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifNotification()
       * );
       */
      toBeValidSarifNotification<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifNotification = buildMatcher<MaybeNotification>({
  matcherName: 'toBeValidSarifNotification',
  definition: 'notification',
});

expect.extend({ toBeValidSarifNotification });
