// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeToolComponent = Sarif.ToolComponent | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ToolComponent}.
       * @example
       * expect(value).toBeValidSarifToolComponent();
       */
      toBeValidSarifToolComponent(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ToolComponent}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifToolComponent()
       * );
       */
      toBeValidSarifToolComponent<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifToolComponent = buildMatcher<MaybeToolComponent>({
  matcherName: 'toBeValidSarifToolComponent',
  definition: 'toolComponent',
});

expect.extend({ toBeValidSarifToolComponent });
