// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeLocation = Sarif.Location | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Location}.
       * @example
       * expect(value).toBeValidSarifLocation();
       */
      toBeValidSarifLocation(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Location}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifLocation()
       * );
       */
      toBeValidSarifLocation<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifLocation = buildMatcher<MaybeLocation>({
  matcherName: 'toBeValidSarifLocation',
  definition: 'location',
});

expect.extend({ toBeValidSarifLocation });
