// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeVersionControlDetails = Sarif.VersionControlDetails | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.VersionControlDetails}.
       * @example
       * expect(value).toBeValidSarifVersionControlDetails();
       */
      toBeValidSarifVersionControlDetails(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.VersionControlDetails}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifVersionControlDetails()
       * );
       */
      toBeValidSarifVersionControlDetails<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifVersionControlDetails = buildMatcher<MaybeVersionControlDetails>({
  matcherName: 'toBeValidSarifVersionControlDetails',
  definition: 'versionControlDetails',
});

expect.extend({ toBeValidSarifVersionControlDetails });
