// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeReportingDescriptor = Sarif.ReportingDescriptor | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ReportingDescriptor}.
       * @example
       * expect(value).toBeValidSarifReportingDescriptor();
       */
      toBeValidSarifReportingDescriptor(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ReportingDescriptor}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifReportingDescriptor()
       * );
       */
      toBeValidSarifReportingDescriptor<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifReportingDescriptor = buildMatcher<MaybeReportingDescriptor>({
  matcherName: 'toBeValidSarifReportingDescriptor',
  definition: 'reportingDescriptor',
});

expect.extend({ toBeValidSarifReportingDescriptor });
