// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeInvocation = Sarif.Invocation | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Invocation}.
       * @example
       * expect(value).toBeValidSarifInvocation();
       */
      toBeValidSarifInvocation(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Invocation}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifInvocation()
       * );
       */
      toBeValidSarifInvocation<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifInvocation = buildMatcher<MaybeInvocation>({
  matcherName: 'toBeValidSarifInvocation',
  definition: 'invocation',
});

expect.extend({ toBeValidSarifInvocation });
