// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeCodeFlow = Sarif.CodeFlow | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.CodeFlow}.
       * @example
       * expect(value).toBeValidSarifCodeFlow();
       */
      toBeValidSarifCodeFlow(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.CodeFlow}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifCodeFlow()
       * );
       */
      toBeValidSarifCodeFlow<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifCodeFlow = buildMatcher<MaybeCodeFlow>({
  matcherName: 'toBeValidSarifCodeFlow',
  definition: 'codeFlow',
});

expect.extend({ toBeValidSarifCodeFlow });
