// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeException = Sarif.Exception | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Exception}.
       * @example
       * expect(value).toBeValidSarifException();
       */
      toBeValidSarifException(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Exception}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifException()
       * );
       */
      toBeValidSarifException<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifException = buildMatcher<MaybeException>({
  matcherName: 'toBeValidSarifException',
  definition: 'exception',
});

expect.extend({ toBeValidSarifException });
