// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeArtifactContent = Sarif.ArtifactContent | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ArtifactContent}.
       * @example
       * expect(value).toBeValidSarifArtifactContent();
       */
      toBeValidSarifArtifactContent(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.ArtifactContent}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifArtifactContent()
       * );
       */
      toBeValidSarifArtifactContent<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifArtifactContent = buildMatcher<MaybeArtifactContent>({
  matcherName: 'toBeValidSarifArtifactContent',
  definition: 'artifactContent',
});

expect.extend({ toBeValidSarifArtifactContent });
