// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeLocationRelationship = Sarif.LocationRelationship | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.LocationRelationship}.
       * @example
       * expect(value).toBeValidSarifLocationRelationship();
       */
      toBeValidSarifLocationRelationship(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.LocationRelationship}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifLocationRelationship()
       * );
       */
      toBeValidSarifLocationRelationship<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifLocationRelationship = buildMatcher<MaybeLocationRelationship>({
  matcherName: 'toBeValidSarifLocationRelationship',
  definition: 'locationRelationship',
});

expect.extend({ toBeValidSarifLocationRelationship });
