// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeReplacement = Sarif.Replacement | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Replacement}.
       * @example
       * expect(value).toBeValidSarifReplacement();
       */
      toBeValidSarifReplacement(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.Replacement}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifReplacement()
       * );
       */
      toBeValidSarifReplacement<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifReplacement = buildMatcher<MaybeReplacement>({
  matcherName: 'toBeValidSarifReplacement',
  definition: 'replacement',
});

expect.extend({ toBeValidSarifReplacement });
