// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeStackFrame = Sarif.StackFrame | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.StackFrame}.
       * @example
       * expect(value).toBeValidSarifStackFrame();
       */
      toBeValidSarifStackFrame(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.StackFrame}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifStackFrame()
       * );
       */
      toBeValidSarifStackFrame<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifStackFrame = buildMatcher<MaybeStackFrame>({
  matcherName: 'toBeValidSarifStackFrame',
  definition: 'stackFrame',
});

expect.extend({ toBeValidSarifStackFrame });
