// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeWebRequest = Sarif.WebRequest | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.WebRequest}.
       * @example
       * expect(value).toBeValidSarifWebRequest();
       */
      toBeValidSarifWebRequest(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.WebRequest}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifWebRequest()
       * );
       */
      toBeValidSarifWebRequest<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifWebRequest = buildMatcher<MaybeWebRequest>({
  matcherName: 'toBeValidSarifWebRequest',
  definition: 'webRequest',
});

expect.extend({ toBeValidSarifWebRequest });
