// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeEdgeTraversal = Sarif.EdgeTraversal | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.EdgeTraversal}.
       * @example
       * expect(value).toBeValidSarifEdgeTraversal();
       */
      toBeValidSarifEdgeTraversal(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is a valid SARIF @type {Sarif.EdgeTraversal}.
       * @example
       * expect(value).toEqual(
       *   expect.toBeValidSarifEdgeTraversal()
       * );
       */
      toBeValidSarifEdgeTraversal<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toBeValidSarifEdgeTraversal = buildMatcher<MaybeEdgeTraversal>({
  matcherName: 'toBeValidSarifEdgeTraversal',
  definition: 'edgeTraversal',
});

expect.extend({ toBeValidSarifEdgeTraversal });
