// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeGraph = Sarif.Graph | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.Graph}.
       * @example
       * expect(value).toMatchSarifGraph();
       */
      toMatchSarifGraph(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.Graph}.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifGraph()
       * );
       */
      toMatchSarifGraph<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifGraph = buildMatcher<MaybeGraph>({
  matcherName: 'toMatchSarifGraph',
  definition: 'graph',
});

expect.extend({ toMatchSarifGraph });
