// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { ArtifactChange } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeArtifactChange = ArtifactChange | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF artifactChange.
       * @example
       * expect(value).toMatchSarifArtifactChange();
       */
      toMatchSarifArtifactChange(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF artifactChange.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifArtifactChange()
       * );
       */
      toMatchSarifArtifactChange<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifArtifactChange = buildMatcher<MaybeArtifactChange>({
  matcherName: 'toMatchSarifArtifactChange',
  definitionName: 'artifactChange',
});

expect.extend({ toMatchSarifArtifactChange });
