// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeStackFrame = Sarif.StackFrame | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.StackFrame}.
       * @example
       * expect(value).toMatchSarifStackFrame();
       */
      toMatchSarifStackFrame(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.StackFrame}.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifStackFrame()
       * );
       */
      toMatchSarifStackFrame<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifStackFrame = buildMatcher<MaybeStackFrame>({
  matcherName: 'toMatchSarifStackFrame',
  definition: 'stackFrame',
});

expect.extend({ toMatchSarifStackFrame });
