// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { MultiformatMessageString } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeMultiformatMessageString = MultiformatMessageString | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF multiformatMessageString.
       * @example
       * expect(value).toMatchSarifMultiformatMessageString();
       */
      toMatchSarifMultiformatMessageString(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF multiformatMessageString.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifMultiformatMessageString()
       * );
       */
      toMatchSarifMultiformatMessageString<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifMultiformatMessageString = buildMatcher<MaybeMultiformatMessageString>({
  matcherName: 'toMatchSarifMultiformatMessageString',
  definitionName: 'multiformatMessageString',
});

expect.extend({ toMatchSarifMultiformatMessageString });
