// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { Message } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeMessage = Message | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF message.
       * @example
       * expect(value).toMatchSarifMessage();
       */
      toMatchSarifMessage(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF message.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifMessage()
       * );
       */
      toMatchSarifMessage<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifMessage = buildMatcher<MaybeMessage>({
  matcherName: 'toMatchSarifMessage',
  definitionName: 'message',
});

expect.extend({ toMatchSarifMessage });
