// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { RunAutomationDetails } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeRunAutomationDetails = RunAutomationDetails | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF runAutomationDetails.
       * @example
       * expect(value).toMatchSarifRunAutomationDetails();
       */
      toMatchSarifRunAutomationDetails(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF runAutomationDetails.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifRunAutomationDetails()
       * );
       */
      toMatchSarifRunAutomationDetails<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifRunAutomationDetails = buildMatcher<MaybeRunAutomationDetails>({
  matcherName: 'toMatchSarifRunAutomationDetails',
  definitionName: 'runAutomationDetails',
});

expect.extend({ toMatchSarifRunAutomationDetails });
