// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { TranslationMetadata } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeTranslationMetadata = TranslationMetadata | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF translationMetadata.
       * @example
       * expect(value).toMatchSarifTranslationMetadata();
       */
      toMatchSarifTranslationMetadata(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF translationMetadata.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifTranslationMetadata()
       * );
       */
      toMatchSarifTranslationMetadata<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifTranslationMetadata = buildMatcher<MaybeTranslationMetadata>({
  matcherName: 'toMatchSarifTranslationMetadata',
  definitionName: 'translationMetadata',
});

expect.extend({ toMatchSarifTranslationMetadata });
