// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeRun = Sarif.Run | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.Run}.
       * @example
       * expect(value).toMatchSarifRun();
       */
      toMatchSarifRun(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.Run}.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifRun()
       * );
       */
      toMatchSarifRun<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifRun = buildMatcher<MaybeRun>({
  matcherName: 'toMatchSarifRun',
  definitionName: 'run',
});

expect.extend({ toMatchSarifRun });
