// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeReportingDescriptor = Sarif.ReportingDescriptor | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.ReportingDescriptor}.
       * @example
       * expect(value).toMatchSarifReportingDescriptor();
       */
      toMatchSarifReportingDescriptor(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.ReportingDescriptor}.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifReportingDescriptor()
       * );
       */
      toMatchSarifReportingDescriptor<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifReportingDescriptor = buildMatcher<MaybeReportingDescriptor>({
  matcherName: 'toMatchSarifReportingDescriptor',
  definitionName: 'reportingDescriptor',
});

expect.extend({ toMatchSarifReportingDescriptor });
