// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { ToolComponentReference } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeToolComponentReference = ToolComponentReference | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF toolComponentReference.
       * @example
       * expect(value).toMatchSarifToolComponentReference();
       */
      toMatchSarifToolComponentReference(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF toolComponentReference.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifToolComponentReference()
       * );
       */
      toMatchSarifToolComponentReference<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifToolComponentReference = buildMatcher<MaybeToolComponentReference>({
  matcherName: 'toMatchSarifToolComponentReference',
  definitionName: 'toolComponentReference',
});

expect.extend({ toMatchSarifToolComponentReference });
