// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { ArtifactLocation } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeArtifactLocation = ArtifactLocation | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF artifactLocation.
       * @example
       * expect(value).toMatchSarifArtifactLocation();
       */
      toMatchSarifArtifactLocation(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF artifactLocation.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifArtifactLocation()
       * );
       */
      toMatchSarifArtifactLocation<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifArtifactLocation = buildMatcher<MaybeArtifactLocation>({
  matcherName: 'toMatchSarifArtifactLocation',
  definitionName: 'artifactLocation',
});

expect.extend({ toMatchSarifArtifactLocation });
