// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { Region } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeRegion = Region | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF region.
       * @example
       * expect(value).toMatchSarifRegion();
       */
      toMatchSarifRegion(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF region.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifRegion()
       * );
       */
      toMatchSarifRegion<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifRegion = buildMatcher<MaybeRegion>({
  matcherName: 'toMatchSarifRegion',
  definitionName: 'region',
});

expect.extend({ toMatchSarifRegion });
