// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { ReportingDescriptorRelationship } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeReportingDescriptorRelationship = ReportingDescriptorRelationship | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF reportingDescriptorRelationship.
       * @example
       * expect(value).toMatchSarifReportingDescriptorRelationship();
       */
      toMatchSarifReportingDescriptorRelationship(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF reportingDescriptorRelationship.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifReportingDescriptorRelationship()
       * );
       */
      toMatchSarifReportingDescriptorRelationship<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifReportingDescriptorRelationship = buildMatcher<MaybeReportingDescriptorRelationship>(
  {
    matcherName: 'toMatchSarifReportingDescriptorRelationship',
    definitionName: 'reportingDescriptorRelationship',
  }
);

expect.extend({ toMatchSarifReportingDescriptorRelationship });
