// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { ReportingConfiguration } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeReportingConfiguration = ReportingConfiguration | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF reportingConfiguration.
       * @example
       * expect(value).toMatchSarifReportingConfiguration();
       */
      toMatchSarifReportingConfiguration(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF reportingConfiguration.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifReportingConfiguration()
       * );
       */
      toMatchSarifReportingConfiguration<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifReportingConfiguration = buildMatcher<MaybeReportingConfiguration>({
  matcherName: 'toMatchSarifReportingConfiguration',
  definitionName: 'reportingConfiguration',
});

expect.extend({ toMatchSarifReportingConfiguration });
