// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { Attachment } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeAttachment = Attachment | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF attachment.
       * @example
       * expect(value).toMatchSarifAttachment();
       */
      toMatchSarifAttachment(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF attachment.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifAttachment()
       * );
       */
      toMatchSarifAttachment<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifAttachment = buildMatcher<MaybeAttachment>({
  matcherName: 'toMatchSarifAttachment',
  definitionName: 'attachment',
});

expect.extend({ toMatchSarifAttachment });
