// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeArtifactLocation = Sarif.ArtifactLocation | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.ArtifactLocation}.
       * @example
       * expect(value).toMatchSarifArtifactLocation();
       */
      toMatchSarifArtifactLocation(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.ArtifactLocation}.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifArtifactLocation()
       * );
       */
      toMatchSarifArtifactLocation<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifArtifactLocation = buildMatcher<MaybeArtifactLocation>({
  matcherName: 'toMatchSarifArtifactLocation',
  definition: 'artifactLocation',
});

expect.extend({ toMatchSarifArtifactLocation });
