// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeExternalPropertyFileReferences = Sarif.ExternalPropertyFileReferences | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.ExternalPropertyFileReferences}.
       * @example
       * expect(value).toMatchSarifExternalPropertyFileReferences();
       */
      toMatchSarifExternalPropertyFileReferences(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.ExternalPropertyFileReferences}.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifExternalPropertyFileReferences()
       * );
       */
      toMatchSarifExternalPropertyFileReferences<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifExternalPropertyFileReferences = buildMatcher<MaybeExternalPropertyFileReferences>(
  {
    matcherName: 'toMatchSarifExternalPropertyFileReferences',
    definitionName: 'externalPropertyFileReferences',
  }
);

expect.extend({ toMatchSarifExternalPropertyFileReferences });
