// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeGraphTraversal = Sarif.GraphTraversal | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.GraphTraversal}.
       * @example
       * expect(value).toMatchSarifGraphTraversal();
       */
      toMatchSarifGraphTraversal(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.GraphTraversal}.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifGraphTraversal()
       * );
       */
      toMatchSarifGraphTraversal<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifGraphTraversal = buildMatcher<MaybeGraphTraversal>({
  matcherName: 'toMatchSarifGraphTraversal',
  definition: 'graphTraversal',
});

expect.extend({ toMatchSarifGraphTraversal });
