// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { PhysicalLocation } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybePhysicalLocation = PhysicalLocation | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF physicalLocation.
       * @example
       * expect(value).toMatchSarifPhysicalLocation();
       */
      toMatchSarifPhysicalLocation(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF physicalLocation.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifPhysicalLocation()
       * );
       */
      toMatchSarifPhysicalLocation<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifPhysicalLocation = buildMatcher<MaybePhysicalLocation>({
  matcherName: 'toMatchSarifPhysicalLocation',
  definitionName: 'physicalLocation',
});

expect.extend({ toMatchSarifPhysicalLocation });
