// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { Exception } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeException = Exception | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF exception.
       * @example
       * expect(value).toMatchSarifException();
       */
      toMatchSarifException(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF exception.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifException()
       * );
       */
      toMatchSarifException<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifException = buildMatcher<MaybeException>({
  matcherName: 'toMatchSarifException',
  definitionName: 'exception',
});

expect.extend({ toMatchSarifException });
