// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { Invocation } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeInvocation = Invocation | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF invocation.
       * @example
       * expect(value).toMatchSarifInvocation();
       */
      toMatchSarifInvocation(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF invocation.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifInvocation()
       * );
       */
      toMatchSarifInvocation<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifInvocation = buildMatcher<MaybeInvocation>({
  matcherName: 'toMatchSarifInvocation',
  definitionName: 'invocation',
});

expect.extend({ toMatchSarifInvocation });
