// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeFix = Sarif.Fix | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.Fix}.
       * @example
       * expect(value).toMatchSarifFix();
       */
      toMatchSarifFix(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.Fix}.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifFix()
       * );
       */
      toMatchSarifFix<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifFix = buildMatcher<MaybeFix>({
  matcherName: 'toMatchSarifFix',
  definitionName: 'fix',
});

expect.extend({ toMatchSarifFix });
