// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { ThreadFlowLocation } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeThreadFlowLocation = ThreadFlowLocation | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF threadFlowLocation.
       * @example
       * expect(value).toMatchSarifThreadFlowLocation();
       */
      toMatchSarifThreadFlowLocation(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF threadFlowLocation.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifThreadFlowLocation()
       * );
       */
      toMatchSarifThreadFlowLocation<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifThreadFlowLocation = buildMatcher<MaybeThreadFlowLocation>({
  matcherName: 'toMatchSarifThreadFlowLocation',
  definitionName: 'threadFlowLocation',
});

expect.extend({ toMatchSarifThreadFlowLocation });
