// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeException = Sarif.Exception | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.Exception}.
       * @example
       * expect(value).toMatchSarifException();
       */
      toMatchSarifException(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.Exception}.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifException()
       * );
       */
      toMatchSarifException<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifException = buildMatcher<MaybeException>({
  matcherName: 'toMatchSarifException',
  definitionName: 'exception',
});

expect.extend({ toMatchSarifException });
