// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { WebRequest } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeWebRequest = WebRequest | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF webRequest.
       * @example
       * expect(value).toMatchSarifWebRequest();
       */
      toMatchSarifWebRequest(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF webRequest.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifWebRequest()
       * );
       */
      toMatchSarifWebRequest<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifWebRequest = buildMatcher<MaybeWebRequest>({
  matcherName: 'toMatchSarifWebRequest',
  definitionName: 'webRequest',
});

expect.extend({ toMatchSarifWebRequest });
