// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeArtifactContent = Sarif.ArtifactContent | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.ArtifactContent}.
       * @example
       * expect(value).toMatchSarifArtifactContent();
       */
      toMatchSarifArtifactContent(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.ArtifactContent}.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifArtifactContent()
       * );
       */
      toMatchSarifArtifactContent<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifArtifactContent = buildMatcher<MaybeArtifactContent>({
  matcherName: 'toMatchSarifArtifactContent',
  definition: 'artifactContent',
});

expect.extend({ toMatchSarifArtifactContent });
