// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeRectangle = Sarif.Rectangle | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.Rectangle}.
       * @example
       * expect(value).toMatchSarifRectangle();
       */
      toMatchSarifRectangle(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.Rectangle}.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifRectangle()
       * );
       */
      toMatchSarifRectangle<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifRectangle = buildMatcher<MaybeRectangle>({
  matcherName: 'toMatchSarifRectangle',
  definitionName: 'rectangle',
});

expect.extend({ toMatchSarifRectangle });
