// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeReportingDescriptorReference = Sarif.ReportingDescriptorReference | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.ReportingDescriptorReference}.
       * @example
       * expect(value).toMatchSarifReportingDescriptorReference();
       */
      toMatchSarifReportingDescriptorReference(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.ReportingDescriptorReference}.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifReportingDescriptorReference()
       * );
       */
      toMatchSarifReportingDescriptorReference<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifReportingDescriptorReference = buildMatcher<MaybeReportingDescriptorReference>(
  {
    matcherName: 'toMatchSarifReportingDescriptorReference',
    definitionName: 'reportingDescriptorReference',
  }
);

expect.extend({ toMatchSarifReportingDescriptorReference });
