// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { Node } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeNode = Node | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF node.
       * @example
       * expect(value).toMatchSarifNode();
       */
      toMatchSarifNode(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF node.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifNode()
       * );
       */
      toMatchSarifNode<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifNode = buildMatcher<MaybeNode>({
  matcherName: 'toMatchSarifNode',
  definitionName: 'node',
});

expect.extend({ toMatchSarifNode });
