// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeNotification = Sarif.Notification | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.Notification}.
       * @example
       * expect(value).toMatchSarifNotification();
       */
      toMatchSarifNotification(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.Notification}.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifNotification()
       * );
       */
      toMatchSarifNotification<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifNotification = buildMatcher<MaybeNotification>({
  matcherName: 'toMatchSarifNotification',
  definitionName: 'notification',
});

expect.extend({ toMatchSarifNotification });
