// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { StackFrame } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeStackFrame = StackFrame | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF stackFrame.
       * @example
       * expect(value).toMatchSarifStackFrame();
       */
      toMatchSarifStackFrame(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF stackFrame.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifStackFrame()
       * );
       */
      toMatchSarifStackFrame<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifStackFrame = buildMatcher<MaybeStackFrame>({
  matcherName: 'toMatchSarifStackFrame',
  definitionName: 'stackFrame',
});

expect.extend({ toMatchSarifStackFrame });
