// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { Graph } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeGraph = Graph | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF graph.
       * @example
       * expect(value).toMatchSarifGraph();
       */
      toMatchSarifGraph(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF graph.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifGraph()
       * );
       */
      toMatchSarifGraph<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifGraph = buildMatcher<MaybeGraph>({
  matcherName: 'toMatchSarifGraph',
  definitionName: 'graph',
});

expect.extend({ toMatchSarifGraph });
