// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { VersionControlDetails } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeVersionControlDetails = VersionControlDetails | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF versionControlDetails.
       * @example
       * expect(value).toMatchSarifVersionControlDetails();
       */
      toMatchSarifVersionControlDetails(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF versionControlDetails.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifVersionControlDetails()
       * );
       */
      toMatchSarifVersionControlDetails<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifVersionControlDetails = buildMatcher<MaybeVersionControlDetails>({
  matcherName: 'toMatchSarifVersionControlDetails',
  definitionName: 'versionControlDetails',
});

expect.extend({ toMatchSarifVersionControlDetails });
