// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeArtifactChange = Sarif.ArtifactChange | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.ArtifactChange}.
       * @example
       * expect(value).toMatchSarifArtifactChange();
       */
      toMatchSarifArtifactChange(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.ArtifactChange}.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifArtifactChange()
       * );
       */
      toMatchSarifArtifactChange<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifArtifactChange = buildMatcher<MaybeArtifactChange>({
  matcherName: 'toMatchSarifArtifactChange',
  definition: 'artifactChange',
});

expect.extend({ toMatchSarifArtifactChange });
