// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { Artifact } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeArtifact = Artifact | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF artifact.
       * @example
       * expect(value).toMatchSarifArtifact();
       */
      toMatchSarifArtifact(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF artifact.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifArtifact()
       * );
       */
      toMatchSarifArtifact<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifArtifact = buildMatcher<MaybeArtifact>({
  matcherName: 'toMatchSarifArtifact',
  definitionName: 'artifact',
});

expect.extend({ toMatchSarifArtifact });
