// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { EdgeTraversal } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeEdgeTraversal = EdgeTraversal | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF edgeTraversal.
       * @example
       * expect(value).toMatchSarifEdgeTraversal();
       */
      toMatchSarifEdgeTraversal(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF edgeTraversal.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifEdgeTraversal()
       * );
       */
      toMatchSarifEdgeTraversal<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifEdgeTraversal = buildMatcher<MaybeEdgeTraversal>({
  matcherName: 'toMatchSarifEdgeTraversal',
  definitionName: 'edgeTraversal',
});

expect.extend({ toMatchSarifEdgeTraversal });
