// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeLocationRelationship = Sarif.LocationRelationship | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.LocationRelationship}.
       * @example
       * expect(value).toMatchSarifLocationRelationship();
       */
      toMatchSarifLocationRelationship(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.LocationRelationship}.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifLocationRelationship()
       * );
       */
      toMatchSarifLocationRelationship<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifLocationRelationship = buildMatcher<MaybeLocationRelationship>({
  matcherName: 'toMatchSarifLocationRelationship',
  definitionName: 'locationRelationship',
});

expect.extend({ toMatchSarifLocationRelationship });
