// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { Address } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeAddress = Address | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF address.
       * @example
       * expect(value).toMatchSarifAddress();
       */
      toMatchSarifAddress(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF address.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifAddress()
       * );
       */
      toMatchSarifAddress<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifAddress = buildMatcher<MaybeAddress>({
  matcherName: 'toMatchSarifAddress',
  definitionName: 'address',
});

expect.extend({ toMatchSarifAddress });
