// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeWebResponse = Sarif.WebResponse | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.WebResponse}.
       * @example
       * expect(value).toMatchSarifWebResponse();
       */
      toMatchSarifWebResponse(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.WebResponse}.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifWebResponse()
       * );
       */
      toMatchSarifWebResponse<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifWebResponse = buildMatcher<MaybeWebResponse>({
  matcherName: 'toMatchSarifWebResponse',
  definitionName: 'webResponse',
});

expect.extend({ toMatchSarifWebResponse });
