// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { CodeFlow } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeCodeFlow = CodeFlow | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF codeFlow.
       * @example
       * expect(value).toMatchSarifCodeFlow();
       */
      toMatchSarifCodeFlow(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF codeFlow.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifCodeFlow()
       * );
       */
      toMatchSarifCodeFlow<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifCodeFlow = buildMatcher<MaybeCodeFlow>({
  matcherName: 'toMatchSarifCodeFlow',
  definitionName: 'codeFlow',
});

expect.extend({ toMatchSarifCodeFlow });
