// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeConfigurationOverride = Sarif.ConfigurationOverride | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.ConfigurationOverride}.
       * @example
       * expect(value).toMatchSarifConfigurationOverride();
       */
      toMatchSarifConfigurationOverride(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.ConfigurationOverride}.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifConfigurationOverride()
       * );
       */
      toMatchSarifConfigurationOverride<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifConfigurationOverride = buildMatcher<MaybeConfigurationOverride>({
  matcherName: 'toMatchSarifConfigurationOverride',
  definition: 'configurationOverride',
});

expect.extend({ toMatchSarifConfigurationOverride });
