// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeEdgeTraversal = Sarif.EdgeTraversal | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.EdgeTraversal}.
       * @example
       * expect(value).toMatchSarifEdgeTraversal();
       */
      toMatchSarifEdgeTraversal(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.EdgeTraversal}.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifEdgeTraversal()
       * );
       */
      toMatchSarifEdgeTraversal<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifEdgeTraversal = buildMatcher<MaybeEdgeTraversal>({
  matcherName: 'toMatchSarifEdgeTraversal',
  definitionName: 'edgeTraversal',
});

expect.extend({ toMatchSarifEdgeTraversal });
