// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { Edge } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeEdge = Edge | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF edge.
       * @example
       * expect(value).toMatchSarifEdge();
       */
      toMatchSarifEdge(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF edge.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifEdge()
       * );
       */
      toMatchSarifEdge<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifEdge = buildMatcher<MaybeEdge>({
  matcherName: 'toMatchSarifEdge',
  definitionName: 'edge',
});

expect.extend({ toMatchSarifEdge });
