// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { Stack } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeStack = Stack | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF stack.
       * @example
       * expect(value).toMatchSarifStack();
       */
      toMatchSarifStack(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF stack.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifStack()
       * );
       */
      toMatchSarifStack<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifStack = buildMatcher<MaybeStack>({
  matcherName: 'toMatchSarifStack',
  definitionName: 'stack',
});

expect.extend({ toMatchSarifStack });
