// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeWebRequest = Sarif.WebRequest | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.WebRequest}.
       * @example
       * expect(value).toMatchSarifWebRequest();
       */
      toMatchSarifWebRequest(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.WebRequest}.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifWebRequest()
       * );
       */
      toMatchSarifWebRequest<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifWebRequest = buildMatcher<MaybeWebRequest>({
  matcherName: 'toMatchSarifWebRequest',
  definition: 'webRequest',
});

expect.extend({ toMatchSarifWebRequest });
