// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeThreadFlow = Sarif.ThreadFlow | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.ThreadFlow}.
       * @example
       * expect(value).toMatchSarifThreadFlow();
       */
      toMatchSarifThreadFlow(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.ThreadFlow}.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifThreadFlow()
       * );
       */
      toMatchSarifThreadFlow<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifThreadFlow = buildMatcher<MaybeThreadFlow>({
  matcherName: 'toMatchSarifThreadFlow',
  definition: 'threadFlow',
});

expect.extend({ toMatchSarifThreadFlow });
