// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeAttachment = Sarif.Attachment | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.Attachment}.
       * @example
       * expect(value).toMatchSarifAttachment();
       */
      toMatchSarifAttachment(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.Attachment}.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifAttachment()
       * );
       */
      toMatchSarifAttachment<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifAttachment = buildMatcher<MaybeAttachment>({
  matcherName: 'toMatchSarifAttachment',
  definitionName: 'attachment',
});

expect.extend({ toMatchSarifAttachment });
