// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { LogicalLocation } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeLogicalLocation = LogicalLocation | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF logicalLocation.
       * @example
       * expect(value).toMatchSarifLogicalLocation();
       */
      toMatchSarifLogicalLocation(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF logicalLocation.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifLogicalLocation()
       * );
       */
      toMatchSarifLogicalLocation<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifLogicalLocation = buildMatcher<MaybeLogicalLocation>({
  matcherName: 'toMatchSarifLogicalLocation',
  definitionName: 'logicalLocation',
});

expect.extend({ toMatchSarifLogicalLocation });
