// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { ExternalPropertyFileReferences } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeExternalPropertyFileReferences = ExternalPropertyFileReferences | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF externalPropertyFileReferences.
       * @example
       * expect(value).toMatchSarifExternalPropertyFileReferences();
       */
      toMatchSarifExternalPropertyFileReferences(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF externalPropertyFileReferences.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifExternalPropertyFileReferences()
       * );
       */
      toMatchSarifExternalPropertyFileReferences<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifExternalPropertyFileReferences = buildMatcher<MaybeExternalPropertyFileReferences>(
  {
    matcherName: 'toMatchSarifExternalPropertyFileReferences',
    definitionName: 'externalPropertyFileReferences',
  }
);

expect.extend({ toMatchSarifExternalPropertyFileReferences });
