// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { Run } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeRun = Run | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF run.
       * @example
       * expect(value).toMatchSarifRun();
       */
      toMatchSarifRun(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF run.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifRun()
       * );
       */
      toMatchSarifRun<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifRun = buildMatcher<MaybeRun>({
  matcherName: 'toMatchSarifRun',
  definitionName: 'run',
});

expect.extend({ toMatchSarifRun });
