// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeRunAutomationDetails = Sarif.RunAutomationDetails | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.RunAutomationDetails}.
       * @example
       * expect(value).toMatchSarifRunAutomationDetails();
       */
      toMatchSarifRunAutomationDetails(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.RunAutomationDetails}.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifRunAutomationDetails()
       * );
       */
      toMatchSarifRunAutomationDetails<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifRunAutomationDetails = buildMatcher<MaybeRunAutomationDetails>({
  matcherName: 'toMatchSarifRunAutomationDetails',
  definition: 'runAutomationDetails',
});

expect.extend({ toMatchSarifRunAutomationDetails });
