// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { Suppression } from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeSuppression = Suppression | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value is an valid SARIF suppression.
       * @example
       * expect(value).toMatchSarifSuppression();
       */
      toMatchSarifSuppression(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value is an valid SARIF suppression.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifSuppression()
       * );
       */
      toMatchSarifSuppression<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifSuppression = buildMatcher<MaybeSuppression>({
  matcherName: 'toMatchSarifSuppression',
  definitionName: 'suppression',
});

expect.extend({ toMatchSarifSuppression });
