// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import * as Sarif from 'sarif';
import { buildMatcher } from '../build-matcher';

type MaybeConversion = Sarif.Conversion | unknown;

declare global {
  namespace jest {
    interface Matchers<R> {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.Conversion}.
       * @example
       * expect(value).toMatchSarifConversion();
       */
      toMatchSarifConversion(): R;
    }
    interface Expect {
      /**
       * Asserts that actual value matches a valid SARIF @type {Sarif.Conversion}.
       * @example
       * expect(value).toEqual(
       *   expect.toMatchSarifConversion()
       * );
       */
      toMatchSarifConversion<T>(): jest.JestMatchers<T>;
    }
  }
}

export const toMatchSarifConversion = buildMatcher<MaybeConversion>({
  matcherName: 'toMatchSarifConversion',
  definition: 'conversion',
});

expect.extend({ toMatchSarifConversion });
