name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    # run linting with our development node/npm versions (per package.json
    # volta config)

    name: 'Lint - ${{ matrix.os }}'
    runs-on: '${{ matrix.os }}-latest'

    strategy:
      matrix:
        os: [windows, ubuntu]

    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - uses: volta-cli/action@efb293bee52c8749b10ecda410b3a3c441fe94d8 # v1.7.1
      - name: install dependencies
        run: npm install
      - name: lint
        run: npm run lint

  test:
    # run linting with our development node/npm versions (per package.json
    # volta config)

    name: 'Tests - Node (${{ matrix.node-version }}) - ${{ matrix.os }}'
    runs-on: '${{ matrix.os }}-latest'

    strategy:
      matrix:
        os: [windows, ubuntu]
        node-version: [14.x, 15.x, 16.x, 17.x]

    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - uses: volta-cli/action@efb293bee52c8749b10ecda410b3a3c441fe94d8 # v1.7.1
      - name: install dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: test
        run: npm test

  floating-dependencies:
    # test using latest allowed dependencies within our semver ranges this is
    # an early warning detection for failures introduced by transitive
    # dependencies

    name: 'Floating Dependencies - ${{ matrix.os }}'
    runs-on: '${{ matrix.os }}-latest'

    strategy:
      matrix:
        os: [windows, ubuntu]

    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - uses: volta-cli/action@efb293bee52c8749b10ecda410b3a3c441fe94d8 # v1.7.1
      - name: install dependencies
        run: npm install --no-package-lock
      - name: build
        run: npm run build
      - name: test
        run: npm test
