name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    # run linting with our development node/npm versions (per package.json
    # volta config)

    name: "Lint - ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}-latest"

    strategy:
      matrix:
        os: [windows, ubuntu]

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: npm ci
      - run: npm run lint

  test:
    # run linting with our development node/npm versions (per package.json
    # volta config)

    name: "Tests - Node (${{ matrix.node-version }}) - ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}-latest"

    strategy:
      matrix:
        os: [windows, ubuntu]
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: npm ci
      - run: npm run build
      - run: npm test

  floating-dependencies:
    # test using latest allowed dependencies within our semver ranges this is
    # an early warning detection for failures introduced by transitive
    # dependencies

    name: "Floating Dependencies - ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}-latest"

    strategy:
      matrix:
        os: [windows, ubuntu]

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: npm install --no-package-lock
      - run: npm run build
      - run: npm test
