name: ESlint sarif formatter test workflow
on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/eslint-formatter-sarif/**'
  workflow_dispatch:

jobs:
  eslint_sarif_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: Install ESLint
        run: |
          npm install eslint
          npm install @microsoft/sarif-multitool

      - name: Install ESLint SARIF formatter dependencies
        run: npm install

      - name: Run local eslint + sarif formatter
        run: npx eslint ./packages/eslint-formatter-sarif
             --ext .js,.jsx,.ts,.tsx
             --format ./packages/eslint-formatter-sarif/sarif.js
             --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload eslint results as artifact
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2.3.1
        with:
          name: eslint-results
          path: eslint-results.sarif

      - name: Validate sarif file
        run: npx @microsoft/sarif-multitool validate eslint-results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@231aa2c8a89117b126725a0e11897209b7118144 # v1.1.39
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true